export const CHATS_UPDATE_ACTION = 'CHATS_LOADED_ACTION';
export const CHAT_UPDATE_ACTION = 'CHAT_LOADED_ACTION';
export const CHATS_LOAD_ACTION = 'CHATS_LOAD_ACTION';
export const MARK_AS_READ_ACTION = 'MARK_AS_READ_ACTION';